//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actueel_weerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actueel_weerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weerstations" type="{}weerstationsType"/>
 *         &lt;element name="buienindex" type="{}buienindexType"/>
 *         &lt;element name="buienradar" type="{}buienradarType"/>
 *         &lt;element name="aantalonweer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aantalhagel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actueel_weerType", propOrder = {
    "weerstations",
    "buienindex",
    "buienradar",
    "aantalonweer",
    "aantalhagel"
})
public class ActueelWeerType {

    @XmlElement(required = true)
    protected WeerstationsType weerstations;
    @XmlElement(required = true)
    protected BuienindexType buienindex;
    @XmlElement(required = true)
    protected BuienradarType buienradar;
    @XmlElement(required = true)
    protected String aantalonweer;
    @XmlElement(required = true)
    protected String aantalhagel;

    /**
     * Gets the value of the weerstations property.
     * 
     * @return
     *     possible object is
     *     {@link WeerstationsType }
     *     
     */
    public WeerstationsType getWeerstations() {
        return weerstations;
    }

    /**
     * Sets the value of the weerstations property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeerstationsType }
     *     
     */
    public void setWeerstations(WeerstationsType value) {
        this.weerstations = value;
    }

    /**
     * Gets the value of the buienindex property.
     * 
     * @return
     *     possible object is
     *     {@link BuienindexType }
     *     
     */
    public BuienindexType getBuienindex() {
        return buienindex;
    }

    /**
     * Sets the value of the buienindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuienindexType }
     *     
     */
    public void setBuienindex(BuienindexType value) {
        this.buienindex = value;
    }

    /**
     * Gets the value of the buienradar property.
     * 
     * @return
     *     possible object is
     *     {@link BuienradarType }
     *     
     */
    public BuienradarType getBuienradar() {
        return buienradar;
    }

    /**
     * Sets the value of the buienradar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuienradarType }
     *     
     */
    public void setBuienradar(BuienradarType value) {
        this.buienradar = value;
    }

    /**
     * Gets the value of the aantalonweer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAantalonweer() {
        return aantalonweer;
    }

    /**
     * Sets the value of the aantalonweer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAantalonweer(String value) {
        this.aantalonweer = value;
    }

    /**
     * Gets the value of the aantalhagel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAantalhagel() {
        return aantalhagel;
    }

    /**
     * Sets the value of the aantalhagel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAantalhagel(String value) {
        this.aantalhagel = value;
    }

}
