//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buienradarType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buienradarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlbackup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icoonactueel" type="{}icoonactueelType"/>
 *         &lt;element name="zonopkomst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zononder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buienradarType", propOrder = {
    "url",
    "urlbackup",
    "icoonactueel",
    "zonopkomst",
    "zononder"
})
public class BuienradarType {

    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String urlbackup;
    @XmlElement(required = true)
    protected IcoonactueelType icoonactueel;
    @XmlElement(required = true)
    protected String zonopkomst;
    @XmlElement(required = true)
    protected String zononder;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the urlbackup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlbackup() {
        return urlbackup;
    }

    /**
     * Sets the value of the urlbackup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlbackup(String value) {
        this.urlbackup = value;
    }

    /**
     * Gets the value of the icoonactueel property.
     * 
     * @return
     *     possible object is
     *     {@link IcoonactueelType }
     *     
     */
    public IcoonactueelType getIcoonactueel() {
        return icoonactueel;
    }

    /**
     * Sets the value of the icoonactueel property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcoonactueelType }
     *     
     */
    public void setIcoonactueel(IcoonactueelType value) {
        this.icoonactueel = value;
    }

    /**
     * Gets the value of the zonopkomst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZonopkomst() {
        return zonopkomst;
    }

    /**
     * Sets the value of the zonopkomst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZonopkomst(String value) {
        this.zonopkomst = value;
    }

    /**
     * Gets the value of the zononder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZononder() {
        return zononder;
    }

    /**
     * Sets the value of the zononder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZononder(String value) {
        this.zononder = value;
    }

}
