//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.bylivingart.plants package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Buienradarnl_QNAME = new QName("", "buienradarnl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bylivingart.plants
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BuienradarnlType }
     */
    public BuienradarnlType createBuienradarnlType() {
        return new BuienradarnlType();
    }

    /**
     * Create an instance of {@link StationnaamType }
     */
    public StationnaamType createStationnaamType() {
        return new StationnaamType();
    }

    /**
     * Create an instance of {@link BuienindexType }
     */
    public BuienindexType createBuienindexType() {
        return new BuienindexType();
    }

    /**
     * Create an instance of {@link VerwachtingMeerdaagsType }
     */
    public VerwachtingMeerdaagsType createVerwachtingMeerdaagsType() {
        return new VerwachtingMeerdaagsType();
    }

    /**
     * Create an instance of {@link DagPlus4Type }
     */
    public DagPlus4Type createDagPlus4Type() {
        return new DagPlus4Type();
    }

    /**
     * Create an instance of {@link DagPlus1Type }
     */
    public DagPlus1Type createDagPlus1Type() {
        return new DagPlus1Type();
    }

    /**
     * Create an instance of {@link WeerstationType }
     */
    public WeerstationType createWeerstationType() {
        return new WeerstationType();
    }

    /**
     * Create an instance of {@link WeerstationsType }
     */
    public WeerstationsType createWeerstationsType() {
        return new WeerstationsType();
    }

    /**
     * Create an instance of {@link VerwachtingVandaagType }
     */
    public VerwachtingVandaagType createVerwachtingVandaagType() {
        return new VerwachtingVandaagType();
    }

    /**
     * Create an instance of {@link IcoonactueelType }
     */
    public IcoonactueelType createIcoonactueelType() {
        return new IcoonactueelType();
    }

    /**
     * Create an instance of {@link WeergegevensType }
     */
    public WeergegevensType createWeergegevensType() {
        return new WeergegevensType();
    }

    /**
     * Create an instance of {@link ActueelWeerType }
     */
    public ActueelWeerType createActueelWeerType() {
        return new ActueelWeerType();
    }

    /**
     * Create an instance of {@link TekstMiddellangType }
     */
    public TekstMiddellangType createTekstMiddellangType() {
        return new TekstMiddellangType();
    }

    /**
     * Create an instance of {@link TekstLangType }
     */
    public TekstLangType createTekstLangType() {
        return new TekstLangType();
    }

    /**
     * Create an instance of {@link DagPlus5Type }
     */
    public DagPlus5Type createDagPlus5Type() {
        return new DagPlus5Type();
    }

    /**
     * Create an instance of {@link DagPlus2Type }
     */
    public DagPlus2Type createDagPlus2Type() {
        return new DagPlus2Type();
    }

    /**
     * Create an instance of {@link IcoonType }
     */
    public IcoonType createIcoonType() {
        return new IcoonType();
    }

    /**
     * Create an instance of {@link DagPlus3Type }
     */
    public DagPlus3Type createDagPlus3Type() {
        return new DagPlus3Type();
    }

    /**
     * Create an instance of {@link ImageType }
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link BuienradarType }
     */
    public BuienradarType createBuienradarType() {
        return new BuienradarType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuienradarnlType }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "buienradarnl")
    public JAXBElement<BuienradarnlType> createBuienradarnl(BuienradarnlType value) {
        return new JAXBElement<BuienradarnlType>(_Buienradarnl_QNAME, BuienradarnlType.class, null, value);
    }

}
