//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verwachting_meerdaagsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="verwachting_meerdaagsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlbackup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tekst_middellang" type="{}tekst_middellangType"/>
 *         &lt;element name="tekst_lang" type="{}tekst_langType"/>
 *         &lt;element name="dag-plus1" type="{}dag-plus1Type"/>
 *         &lt;element name="dag-plus2" type="{}dag-plus2Type"/>
 *         &lt;element name="dag-plus3" type="{}dag-plus3Type"/>
 *         &lt;element name="dag-plus4" type="{}dag-plus4Type"/>
 *         &lt;element name="dag-plus5" type="{}dag-plus5Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verwachting_meerdaagsType", propOrder = {
        "url",
        "urlbackup",
        "tekstMiddellang",
        "tekstLang",
        "dagPlus1",
        "dagPlus2",
        "dagPlus3",
        "dagPlus4",
        "dagPlus5"
})
public class VerwachtingMeerdaagsType {

    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String urlbackup;
    @XmlElement(name = "tekst_middellang", required = true)
    protected TekstMiddellangType tekstMiddellang;
    @XmlElement(name = "tekst_lang", required = true)
    protected TekstLangType tekstLang;
    @XmlElement(name = "dag-plus1", required = true)
    protected DagPlus1Type dagPlus1;
    @XmlElement(name = "dag-plus2", required = true)
    protected DagPlus2Type dagPlus2;
    @XmlElement(name = "dag-plus3", required = true)
    protected DagPlus3Type dagPlus3;
    @XmlElement(name = "dag-plus4", required = true)
    protected DagPlus4Type dagPlus4;
    @XmlElement(name = "dag-plus5", required = true)
    protected DagPlus5Type dagPlus5;

    /**
     * Gets the value of the url property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the urlbackup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUrlbackup() {
        return urlbackup;
    }

    /**
     * Sets the value of the urlbackup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUrlbackup(String value) {
        this.urlbackup = value;
    }

    /**
     * Gets the value of the tekstMiddellang property.
     *
     * @return possible object is
     * {@link TekstMiddellangType }
     */
    public TekstMiddellangType getTekstMiddellang() {
        return tekstMiddellang;
    }

    /**
     * Sets the value of the tekstMiddellang property.
     *
     * @param value allowed object is
     *              {@link TekstMiddellangType }
     */
    public void setTekstMiddellang(TekstMiddellangType value) {
        this.tekstMiddellang = value;
    }

    /**
     * Gets the value of the tekstLang property.
     *
     * @return possible object is
     * {@link TekstLangType }
     */
    public TekstLangType getTekstLang() {
        return tekstLang;
    }

    /**
     * Sets the value of the tekstLang property.
     *
     * @param value allowed object is
     *              {@link TekstLangType }
     */
    public void setTekstLang(TekstLangType value) {
        this.tekstLang = value;
    }

    /**
     * Gets the value of the dagPlus1 property.
     *
     * @return possible object is
     * {@link DagPlus1Type }
     */
    public DagPlus1Type getDagPlus1() {
        return dagPlus1;
    }

    /**
     * Sets the value of the dagPlus1 property.
     *
     * @param value allowed object is
     *              {@link DagPlus1Type }
     */
    public void setDagPlus1(DagPlus1Type value) {
        this.dagPlus1 = value;
    }

    /**
     * Gets the value of the dagPlus2 property.
     *
     * @return possible object is
     * {@link DagPlus2Type }
     */
    public DagPlus2Type getDagPlus2() {
        return dagPlus2;
    }

    /**
     * Sets the value of the dagPlus2 property.
     *
     * @param value allowed object is
     *              {@link DagPlus2Type }
     */
    public void setDagPlus2(DagPlus2Type value) {
        this.dagPlus2 = value;
    }

    /**
     * Gets the value of the dagPlus3 property.
     *
     * @return possible object is
     * {@link DagPlus3Type }
     */
    public DagPlus3Type getDagPlus3() {
        return dagPlus3;
    }

    /**
     * Sets the value of the dagPlus3 property.
     *
     * @param value allowed object is
     *              {@link DagPlus3Type }
     */
    public void setDagPlus3(DagPlus3Type value) {
        this.dagPlus3 = value;
    }

    /**
     * Gets the value of the dagPlus4 property.
     *
     * @return possible object is
     * {@link DagPlus4Type }
     */
    public DagPlus4Type getDagPlus4() {
        return dagPlus4;
    }

    /**
     * Sets the value of the dagPlus4 property.
     *
     * @param value allowed object is
     *              {@link DagPlus4Type }
     */
    public void setDagPlus4(DagPlus4Type value) {
        this.dagPlus4 = value;
    }

    /**
     * Gets the value of the dagPlus5 property.
     *
     * @return possible object is
     * {@link DagPlus5Type }
     */
    public DagPlus5Type getDagPlus5() {
        return dagPlus5;
    }

    /**
     * Sets the value of the dagPlus5 property.
     *
     * @param value allowed object is
     *              {@link DagPlus5Type }
     */
    public void setDagPlus5(DagPlus5Type value) {
        this.dagPlus5 = value;
    }

}
