//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verwachting_vandaagType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="verwachting_vandaagType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlbackup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tijdweerbericht" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="samenvatting" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formattedtekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verwachting_vandaagType", propOrder = {
    "url",
    "urlbackup",
    "titel",
    "tijdweerbericht",
    "samenvatting",
    "tekst",
    "formattedtekst"
})
public class VerwachtingVandaagType {

    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String urlbackup;
    @XmlElement(required = true)
    protected String titel;
    @XmlElement(required = true)
    protected String tijdweerbericht;
    @XmlElement(required = true)
    protected String samenvatting;
    @XmlElement(required = true)
    protected String tekst;
    @XmlElement(required = true)
    protected String formattedtekst;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the urlbackup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlbackup() {
        return urlbackup;
    }

    /**
     * Sets the value of the urlbackup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlbackup(String value) {
        this.urlbackup = value;
    }

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the tijdweerbericht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTijdweerbericht() {
        return tijdweerbericht;
    }

    /**
     * Sets the value of the tijdweerbericht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTijdweerbericht(String value) {
        this.tijdweerbericht = value;
    }

    /**
     * Gets the value of the samenvatting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamenvatting() {
        return samenvatting;
    }

    /**
     * Sets the value of the samenvatting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamenvatting(String value) {
        this.samenvatting = value;
    }

    /**
     * Gets the value of the tekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekst(String value) {
        this.tekst = value;
    }

    /**
     * Gets the value of the formattedtekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedtekst() {
        return formattedtekst;
    }

    /**
     * Sets the value of the formattedtekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedtekst(String value) {
        this.formattedtekst = value;
    }

}
