//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 05:46:22 PM CEST 
//


package com.bylivingart.plants.buienradar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for weerstationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="weerstationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stationcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stationnaam" type="{}stationnaamType"/>
 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="luchtvochtigheid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="temperatuurGC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="windsnelheidMS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="windsnelheidBF">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="-"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="windrichtingGR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="windrichting">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="O"/>
 *               &lt;enumeration value="OZO"/>
 *               &lt;enumeration value="NO"/>
 *               &lt;enumeration value="ONO"/>
 *               &lt;enumeration value="ZO"/>
 *               &lt;enumeration value="NNO"/>
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="ZZO"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="luchtdruk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zichtmeters" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="windstotenMS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regenMMPU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zonintensiteitWM2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icoonactueel" type="{}icoonactueelType"/>
 *         &lt;element name="temperatuur10cm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latGraden" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lonGraden" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "weerstationType", propOrder = {
    "stationcode",
    "stationnaam",
    "lat",
    "lon",
    "datum",
    "luchtvochtigheid",
    "temperatuurGC",
    "windsnelheidMS",
    "windsnelheidBF",
    "windrichtingGR",
    "windrichting",
    "luchtdruk",
    "zichtmeters",
    "windstotenMS",
    "regenMMPU",
    "zonintensiteitWM2",
    "icoonactueel",
    "temperatuur10Cm",
    "url",
    "latGraden",
    "lonGraden"
})
public class WeerstationType {

    @XmlElement(required = true)
    protected String stationcode;
    @XmlElement(required = true)
    protected StationnaamType stationnaam;
    @XmlElement(required = true)
    protected String lat;
    @XmlElement(required = true)
    protected String lon;
    @XmlElement(required = true)
    protected String datum;
    @XmlElement(required = true)
    protected String luchtvochtigheid;
    @XmlElement(required = true)
    protected String temperatuurGC;
    @XmlElement(required = true)
    protected String windsnelheidMS;
    @XmlElement(required = true)
    protected String windsnelheidBF;
    @XmlElement(required = true)
    protected String windrichtingGR;
    @XmlElement(required = true)
    protected String windrichting;
    @XmlElement(required = true)
    protected String luchtdruk;
    @XmlElement(required = true)
    protected String zichtmeters;
    @XmlElement(required = true)
    protected String windstotenMS;
    @XmlElement(required = true)
    protected String regenMMPU;
    @XmlElement(required = true)
    protected String zonintensiteitWM2;
    @XmlElement(required = true)
    protected IcoonactueelType icoonactueel;
    @XmlElement(name = "temperatuur10cm", required = true)
    protected String temperatuur10Cm;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String latGraden;
    @XmlElement(required = true)
    protected String lonGraden;
    @XmlAttribute(name = "id")
    protected String id;

    public WeerstationType(){};

    public WeerstationType(
        String stationcode, 
        StationnaamType stationnaam, 
        String lat, 
        String lon, 
        String datum, 
        String luchtvochtigheid, 
        String temperatuurGC, 
        String windsnelheidMS, 
        String windsnelheidBF, 
        String windrichtingGR, 
        String windrichting, 
        String luchtdruk, 
        String zichtmeters, 
        String windstotenMS,
        String regenMMPU, 
        String zonintensiteitWM2, 
        IcoonactueelType icoonactueel, 
        String temperatuur10Cm, 
        String url, 
        String latGraden, 
        String lonGraden, 
        String id){
            this.stationcode = stationcode;
            this.stationnaam = stationnaam;
            this.lat = lat;
            this.lon = lon;
            this.datum = datum;
            this.luchtvochtigheid = luchtvochtigheid;
            this.temperatuurGC = temperatuurGC;
            this.windsnelheidMS = windsnelheidMS;
            this.windsnelheidBF = windsnelheidBF;
            this.windrichtingGR = windrichtingGR;
            this.windrichting = windrichting;
            this.luchtdruk = luchtdruk;
            this.zichtmeters = zichtmeters;
            this.windstotenMS = windstotenMS;
            this.regenMMPU = regenMMPU;
            this.zonintensiteitWM2 = zonintensiteitWM2;
            this.icoonactueel = icoonactueel;
            this.temperatuur10Cm = temperatuur10Cm;
            this.url = url;
            this.latGraden = latGraden;
            this.lonGraden = lonGraden;
            this.id = id;
    }

    /**
     * Gets the value of the stationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationcode() {
        return stationcode;
    }

    /**
     * Sets the value of the stationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationcode(String value) {
        this.stationcode = value;
    }

    /**
     * Gets the value of the stationnaam property.
     * 
     * @return
     *     possible object is
     *     {@link StationnaamType }
     *     
     */
    public StationnaamType getStationnaam() {
        return stationnaam;
    }

    /**
     * Sets the value of the stationnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link StationnaamType }
     *     
     */
    public void setStationnaam(StationnaamType value) {
        this.stationnaam = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLon(String value) {
        this.lon = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the luchtvochtigheid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuchtvochtigheid() {
        return luchtvochtigheid;
    }

    /**
     * Sets the value of the luchtvochtigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuchtvochtigheid(String value) {
        this.luchtvochtigheid = value;
    }

    /**
     * Gets the value of the temperatuurGC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatuurGC() {
        return temperatuurGC;
    }

    /**
     * Sets the value of the temperatuurGC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatuurGC(String value) {
        this.temperatuurGC = value;
    }

    /**
     * Gets the value of the windsnelheidMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindsnelheidMS() {
        return windsnelheidMS;
    }

    /**
     * Sets the value of the windsnelheidMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindsnelheidMS(String value) {
        this.windsnelheidMS = value;
    }

    /**
     * Gets the value of the windsnelheidBF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindsnelheidBF() {
        return windsnelheidBF;
    }

    /**
     * Sets the value of the windsnelheidBF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindsnelheidBF(String value) {
        this.windsnelheidBF = value;
    }

    /**
     * Gets the value of the windrichtingGR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindrichtingGR() {
        return windrichtingGR;
    }

    /**
     * Sets the value of the windrichtingGR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindrichtingGR(String value) {
        this.windrichtingGR = value;
    }

    /**
     * Gets the value of the windrichting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindrichting() {
        return windrichting;
    }

    /**
     * Sets the value of the windrichting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindrichting(String value) {
        this.windrichting = value;
    }

    /**
     * Gets the value of the luchtdruk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuchtdruk() {
        return luchtdruk;
    }

    /**
     * Sets the value of the luchtdruk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuchtdruk(String value) {
        this.luchtdruk = value;
    }

    /**
     * Gets the value of the zichtmeters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZichtmeters() {
        return zichtmeters;
    }

    /**
     * Sets the value of the zichtmeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZichtmeters(String value) {
        this.zichtmeters = value;
    }

    /**
     * Gets the value of the windstotenMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindstotenMS() {
        return windstotenMS;
    }

    /**
     * Sets the value of the windstotenMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindstotenMS(String value) {
        this.windstotenMS = value;
    }

    /**
     * Gets the value of the regenMMPU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegenMMPU() {
        return regenMMPU;
    }

    /**
     * Sets the value of the regenMMPU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegenMMPU(String value) {
        this.regenMMPU = value;
    }

    /**
     * Gets the value of the zonintensiteitWM2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZonintensiteitWM2() {
        return zonintensiteitWM2;
    }

    /**
     * Sets the value of the zonintensiteitWM2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZonintensiteitWM2(String value) {
        this.zonintensiteitWM2 = value;
    }

    /**
     * Gets the value of the icoonactueel property.
     * 
     * @return
     *     possible object is
     *     {@link IcoonactueelType }
     *     
     */
    public IcoonactueelType getIcoonactueel() {
        return icoonactueel;
    }

    /**
     * Sets the value of the icoonactueel property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcoonactueelType }
     *     
     */
    public void setIcoonactueel(IcoonactueelType value) {
        this.icoonactueel = value;
    }

    /**
     * Gets the value of the temperatuur10Cm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatuur10Cm() {
        return temperatuur10Cm;
    }

    /**
     * Sets the value of the temperatuur10Cm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatuur10Cm(String value) {
        this.temperatuur10Cm = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the latGraden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatGraden() {
        return latGraden;
    }

    /**
     * Sets the value of the latGraden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatGraden(String value) {
        this.latGraden = value;
    }

    /**
     * Gets the value of the lonGraden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLonGraden() {
        return lonGraden;
    }

    /**
     * Sets the value of the lonGraden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLonGraden(String value) {
        this.lonGraden = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
