package com.bylivingart.plants.controllers;

import com.bylivingart.plants.DatabaseConnection;
import com.bylivingart.plants.Exceptions.BadRequestException;
import com.bylivingart.plants.Exceptions.UnauthorizedException;
import com.bylivingart.plants.dataclasses.User;
import com.bylivingart.plants.statements.UserStatements;
import io.swagger.annotations.*;
import io.swagger.models.Response;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.sql.Connection;
import java.util.ArrayList;

@Api(value = "User controller")
@RestController
@RequestMapping("/api")
public class UserController {
    @ApiOperation(value = "Get a list of users")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully retrieved list", response = User.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 401, message = "Invalid credentials", response = Error.class),
            @ApiResponse(code = 403, message = "forbidden", response = Error.class),
            @ApiResponse(code = 404, message = "No data in database", response = Error.class)
    })
    @GetMapping("/users/getall")
    private ResponseEntity<ArrayList<User>> getAllUsers() throws Exception {
        Connection conn = new DatabaseConnection().getConnection();
        ResponseEntity<ArrayList<User>> response = new ResponseEntity<>(UserStatements.getAllUsers(conn), HttpStatus.OK);
        conn.close();
        return response;
    }

    @ApiOperation(value = "Check the user password")
    @ApiResponses(value = {
            @ApiResponse(code = 204, message = "User password is correct"),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 404, message = "User not found", response = Error.class)
    })
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @GetMapping("/checkpassword")
    private ResponseEntity<Void> checkUserPassword(String userName, String password) throws Exception{
        Connection conn = new DatabaseConnection().getConnection();
        if (UserStatements.checkUserPassword(password, userName, conn)) {
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
        } else {
            throw new UnauthorizedException("UserName or Password is wrong");
        }
    }

    @ApiOperation(value = "Create a new User")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully retrieved list", response = User.class),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 401, message = "Invalid credentials", response = Error.class),
            @ApiResponse(code = 403, message = "forbidden", response = Error.class),
            @ApiResponse(code = 404, message = "User not found", response = Error.class)
    })
    @PostMapping("/users")
    private ResponseEntity<User> createUser(
            @ApiParam(value = "Authority is defaulted to 'ROLE_USER' and id is autogenerated") @RequestBody User user
    ) throws Exception {
        Connection conn = new DatabaseConnection().getConnection();
        ResponseEntity<User> response = new ResponseEntity<>(UserStatements.createUser(user, conn), HttpStatus.OK);
        conn.close();
        return response;
    }

    // Update a certain object
    @ApiOperation(value = "Update an User object")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully updated the User object", response = User.class),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 401, message = "Bad credentials", response = Error.class),
            @ApiResponse(code = 403, message = "forbidden", response = Error.class),
            @ApiResponse(code = 404, message = "User not found", response = Error.class)
    })
    @PutMapping("/users/{id}")
    private ResponseEntity<User> updateUser(
            @ApiParam(value = "Id of the User that you want to update", required = true) @PathVariable Integer id,
            @ApiParam(value = "The object with the User that you want to update", required = true) @RequestBody User user,
            HttpServletRequest request
    ) throws Exception {
        if (id.equals(user.getId())) {
            Connection conn = new DatabaseConnection().getConnection();
            User result = UserStatements.updateUser(user, conn, request);
            conn.close();
            return new ResponseEntity<>(result, HttpStatus.OK);
        } else {
            throw new BadRequestException("ID's are different");
        }
    }

    // Delete a certain address object.
    @ApiOperation(value = "Delete a user", response = User.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully deleted the user", response = User.class),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 401, message = "Bad credentials", response = Error.class),
            @ApiResponse(code = 403, message = "forbidden", response = Error.class),
            @ApiResponse(code = 404, message = "User not found", response = Error.class)
    })
    @DeleteMapping("/users/")
    private ResponseEntity<User> deleteUser(
            HttpServletRequest request
    ) throws Exception {
        Connection conn = new DatabaseConnection().getConnection();
        ResponseEntity<User> response = new ResponseEntity<>(UserStatements.deleteUser(conn, request), HttpStatus.OK);
        conn.close();
        return response;
    }
}
